### PR TITLE
Updated 0302 document

### PR DESCRIPTION
**Pull request by sonalika-roy**
## Purpose
All app logs
Customer-service app logs
Spring Cloud Config Server logs
Spring Cloud Service Registry lo
* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by sonalika-roy** [comment]
I have not added query for : 
All exceptions
All inbound calls into apps on Azure Container Apps

Not sure if we can get this from console and system logs.It's something we can get from app insights. Still looking into it.

**Comment by vermegi** [comment]
I'll hold off on the approval and merge until you looked into 
All exceptions
All inbound calls into apps on Azure Container Apps
Unless you prefer to already merge, your call.

**Comment by vermegi** [comment]
fixes #35

**Comment by sonalika-roy** [comment]
@vermegi : I don't see anything in logs which will show all inbound calls. I have added anything else and we can merge it for now.

**Review by vermegi — APPROVED** [review]
LGTM

**Pull request merged**
