### PR TITLE
PostgreSQL binding for Spring-Petclinic-Microservices

### PR DESCRIPTION
**Pull request by selvasingh**
This unit is by Spektra to add PostgreSQL binding for the sample app.

### CODE REVIEW

**Comment by selvasingh** [comment]
@Aryan-CC please add necessary instructions for the PostgreSQL binding

**Comment by sonwan2020** [comment]
I am ok with this PR
What's the plan to update the app configurations and the guides to use postgresql?

**Comment by Aryan-CC** [comment]
Hi @selvasingh, 

Do you want me to add the instructions for PostgreSQL configurations in docs directory of this repository?

If yes, do you want me to create a new files for PostgreSQL instructions?

**Comment by selvasingh** [comment]
yes as discussed

**Review by sonwan2020 — APPROVED** [review]

**Pull request merged**
